### PR TITLE
Add documentation on the proposed Firebase schema

### PR DESCRIPTION
**Pull request by jasonpetsod**
This change is [Reviewable](https://reviewable.io/reviews/jasonpetsod/loony/1)

### CODE REVIEW

**Comment by witriew** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[prototype2/frontend/doc/schema.md, line 10 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcR8mOFFZOimMqgoGJW:-KcR8mOFFZOimMqgoGJX:bcbzr2g) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L10)):*
> users/
>   // Key provided by firebase.database.Reference.push() .
>   $userId/

Is this meant to be separate users or separate whole-budgets?  If users, need more fields like name, desc, etc.?

---

*[prototype2/frontend/doc/schema.md, line 33 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRE_9ViX3zM8lEPalN:-KcRE_9ViX3zM8lEPalO:b-nwona7) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L33)):*
> // Whether the account appears in the UI and the user can attribute
> // transactions to it. Can be toggled by the user to hide accounts
> // that are no longer in use.

Will this affect the net-budget totals as well?

---

*[prototype2/frontend/doc/schema.md, line 55 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGRJQKNI7yyddbCXY:-KcRGRJQKNI7yyddbCXZ:bivr35w) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L55)):*
> $month/

Should this have a `workingMinor  int` as well?

---

*[prototype2/frontend/doc/schema.md, line 66 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGZSrpypAEiSHAdKF:-KcRGZSrpypAEiSHAdKG:buum374) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L66)):*
> ```Markdown
>     payees/
>       // Provided by firebase.database.Reference.push() .
>       $payeeId/
> ```

I *half* enjoyed the auto-filled payee based on location (when it worked).  Should that be stored here?  Or maybe do this like the new Swarm UI (find places near me) in the UX?

---

*[prototype2/frontend/doc/schema.md, line 75 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRIFZ5LLvQ-XrRHjwV:-KcRIFZ5LLvQ-XrRHjwW:bpbslb3) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L75)):*
> ```Markdown
>     categories/
>       // Provided by firebase.database.Reference.push() .
>       $categoryId/
> ```

Nested categories?

---

*[prototype2/frontend/doc/schema.md, line 90 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRXBTe2Wdc-Csu9YBz:-KcRXBTe2Wdc-Csu9YC-:bxtpd07) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L90)):*
> $month/

Should this be like every other field that's a key (provided by *.push()) and push the monthFmt down to a field?

---

*[prototype2/frontend/doc/schema.md, line 192 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcROlUopgaQ7BGQfgaH:-KcROlUopgaQ7BGQfgaI:bm3wyrt) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L192)):*
>   // The minimum client version that's allowed to access the database. Clients
>   // must refuse to read or write if their version < minAllowed. Incremented for
>   // changes that are not backwards-compatible.
>   minAllowed int
>  
>   // The maximum client version that will show a deprecation warning. Clients
>   // should show a notice to the user warning them to update to the latest
>   // version if their version <= deprecated. minAllowed <= deprecated.
>   deprecated int

Is this actually required at this level?  The clients should be the one responsible for determining whether they can communicate with the current version (or backwards compatible) with those versions of the schema.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by jasonpetsod** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[prototype2/frontend/doc/schema.md, line 1 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcSeMCppzacOwT972zW:-KcSeMCppzacOwT972zX:bw0pn4z) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L1)):*
> ```Markdown
> # Database schema
> ```

Need to move this file to /doc/schema.md once all comments are addressed.

---

*[prototype2/frontend/doc/schema.md, line 10 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcR8mOFFZOimMqgoGJW:-KcSe5KXR9-MCaX7Nqyd:bfh0ul7) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L10)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

> users/
>   // Key provided by firebase.database.Reference.push() .
>   $userId/

Is this meant to be separate users or separate whole-budgets?  If users, need more fields like name, desc, etc.?
</blockquote></details>

Ah shoot, I guess we gotta have separate entire budgets. Should we add another level `/users/$userId/budgets/$budgetId/` and put everything here under it?

---

*[prototype2/frontend/doc/schema.md, line 33 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRE_9ViX3zM8lEPalN:-KcSgWO4WyKHNXoUzNxJ:bjakjzt) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L33)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

> // Whether the account appears in the UI and the user can attribute
> // transactions to it. Can be toggled by the user to hide accounts
> // that are no longer in use.

Will this affect the net-budget totals as well?
</blockquote></details>

Which total specifically?

Maybe we should enforce that closed accounts have `clearedAmountMinor == 0` before they're able to be closed.

---

*[prototype2/frontend/doc/schema.md, line 55 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGRJQKNI7yyddbCXY:-KcSegeVgGBRbIC9HjhB:b7xepi9) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L55)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

> $month/

Should this have a `workingMinor  int` as well?
</blockquote></details>

No strong preference. This part of the tree is only an optimization for reports, right? Do we care about uncleared transactions as part of reports?

---

*[prototype2/frontend/doc/schema.md, line 66 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGZSrpypAEiSHAdKF:-KcShAsQtmmfvGp_REEp:b-s2vrku) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L66)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

I *half* enjoyed the auto-filled payee based on location (when it worked).  Should that be stored here?  Or maybe do this like the new Swarm UI (find places near me) in the UX?
</blockquote></details>

Yup, agree. We probably want to use a combination of this: the app could use both the Foursquare API and historical locations stored here to suggest to the user which places are nearby. If the user chooses a place, we store its latitude and longitude here for future use. If the user doesn't choose a place listed in Foursquare, we store the current location attributed to the payee.

We'd need some sort of reverse geo-search though. Firebase doesn't give one to us for free so we'd need to come up with a new schema that can be searched efficiently for this.

Can I add a TODO here as a placeholder?

---

*[prototype2/frontend/doc/schema.md, line 75 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRIFZ5LLvQ-XrRHjwV:-KcShRQr4yg_adjj1GIE:b1s9yx6) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L75)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

Nested categories?
</blockquote></details>

Right, yeah. Added a `parentId` field.

---

*[prototype2/frontend/doc/schema.md, line 90 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRXBTe2Wdc-Csu9YBz:-KcSpYyJKHkA4VQmxhk1:b-fjjwa3) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L90)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

> $month/

Should this be like every other field that's a key (provided by *.push()) and push the monthFmt down to a field?
</blockquote></details>

Well these keys are gonna be unique right? It seems like it's a little more straightforward to set up `firebase.database().ref('.../budgets/2017-01').on(...)` than `firebase.database().ref('.../budgets').equalTo(monthFmt, '2017-01').on(...)`. No strong preference.

---

*[prototype2/frontend/doc/schema.md, line 192 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcROlUopgaQ7BGQfgaH:-KcShgyRKR_i6RJqejlR:b-70o16i) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L192)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

>   // The minimum client version that's allowed to access the database. Clients
>   // must refuse to read or write if their version < minAllowed. Incremented for
>   // changes that are not backwards-compatible.
>   minAllowed int
>  
>   // The maximum client version that will show a deprecation warning. Clients
>   // should show a notice to the user warning them to update to the latest
>   // version if their version <= deprecated. minAllowed <= deprecated.
>   deprecated int

Is this actually required at this level?  The clients should be the one responsible for determining whether they can communicate with the current version (or backwards compatible) with those versions of the schema.
</blockquote></details>

Clients won't know if we've completely removed old fields or backfilled existing fields with a different format in the working database just by looking at their version number though.

I'm envisioning a process kinda like this:
1. Dream up a new change to the schema.
1. Add a new constant in `dbVersions.js` or something that's one more than the previous largest version. The constant is named for the new feature supported by the schema.
1. Whenever we push we set `head` in the database to the largest version in `dbVersions.js` to indicate that new fields may start to be written. (I don't think the client needs to read this field; it's just an annotation to operators when we look at the database manually.)
1. Client at source `HEAD` starts writing entries in both the new and the old schema. It still treats the old version of the schema as authoritative and only reads from the old schema (not all entries have been backfilled yet). If the new version fields are present, it'll compare the old and new and emit an error if they differ (e.g. bug in the write path).
1. We set `deprecated` in the database to the last version that does _not_ write the entries in the new schema.
1. We backfill all existing entries to have the new schema.
1. Client at source `HEAD` starts reading entries in the new format. It still continues to write data in the old schema though and compare new and old versions.
1. Right before we perform the final backfill, we set `minAllowed` to the same as `deprecated`. hm, I guess we'll need to have some amount of time for this to propagate to clients: we probably don't want them to read `minAllowed` on every database operation. Maybe force them to read this field every, say, hour? When we want to kill off old clients, we increment this field, wait a little more than an hour, and then perform the final backfill. I thought about adding an `effectiveDateMs` sub-field here to indicate the timestamp at which a breaking schema change would go into effect but we can't trust client clocks.
1. Perform the final backfill to fix up entries that old clients have been writing since the first backfill.
1. Once we're confident that there's not gonna be a client rollback, perform a cleanup backfill to remove the old fields. Remove the old constants from `dbVersions.js`.

(Yes, completely overengineered for an app that probably only you and me will use, but oh well!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by jasonpetsod** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[prototype2/frontend/doc/schema.md, line 90 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRXBTe2Wdc-Csu9YBz:-KcSwsnuWOcwvHV2oP_a:b-6jsrue) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L90)):*
<details><summary><i>Previously, jasonpetsod (Jason Petsod) wrote…</i></summary><blockquote>

Well these keys are gonna be unique right? It seems like it's a little more straightforward to set up `firebase.database().ref('.../budgets/2017-01').on(...)` than `firebase.database().ref('.../budgets').equalTo(monthFmt, '2017-01').on(...)`. No strong preference.
</blockquote></details>

Er, I guess what I said doesn't make sense. We'd set up listeners on `.../budgets/$budgetId/{accounts,categories,payees,transactions}/` and merge all the changes with `this.setState()`. No need to set a listener so deep into the tree.

No strong preference here then.

---

*[prototype2/frontend/doc/schema.md, line 192 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcROlUopgaQ7BGQfgaH:-KcSxeqOoapo6Q5mkU8u:bo0ljmm) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L192)):*
> Maybe force them to read this field every, say, hour? When we want to kill off old clients, we increment this field, wait a little more than an hour, and then perform the final backfill.

Well, Firebase is _REALTIME_ so we'd set up a listener on `/schemaVersions/` and clients should pick it up "quickly". Probably worth waiting a few minutes for everyone to synchronize nonetheless.

We'll want to set deadlines on transactions though.

Maybe the database isn't the right place for this data. We want this to be ~synchronous but also not require database transactions against `/` to read `minAllowedVersion` _and_ set something deep within e.g. `/users/$userId/budgets/$budgetId/transactions/$txId/`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by witriew** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[prototype2/frontend/doc/schema.md, line 10 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcR8mOFFZOimMqgoGJW:-KcUBIARvE2IgpxP-ouI:b-tfbrn7) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L10)):*
<details><summary><i>Previously, jasonpetsod (Jason Petsod) wrote…</i></summary><blockquote>

Ah shoot, I guess we gotta have separate entire budgets. Should we add another level `/users/$userId/budgets/$budgetId/` and put everything here under it?
</blockquote></details>

Yeah, why not.  I can't think of a better way to do it right now.  It feels like we're hitting too many levels of nesting, though.

---

*[prototype2/frontend/doc/schema.md, line 33 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRE_9ViX3zM8lEPalN:-KcRAHJuIT-KCwqrbnUC:bdap6ci) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L33)):*
> Which total specifically?

As in budget and non-budget accounts.  Once it's hidden, that account no longer considered to be part of that budget.

Separately from that, I think this falls under separation of concerns.  Whether items should get hidden in the UI or not should be saved at the client (cookie/local data/whatever), not within the DB.

---

*[prototype2/frontend/doc/schema.md, line 55 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGRJQKNI7yyddbCXY:-KcU9ws8RjA_EAh2bpL4:bhdwa0x) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L55)):*
<details><summary><i>Previously, jasonpetsod (Jason Petsod) wrote…</i></summary><blockquote>

No strong preference. This part of the tree is only an optimization for reports, right? Do we care about uncleared transactions as part of reports?
</blockquote></details>

The worry is that a transaction may not be cleared until X months later.  In which case, it's likely that we'll need to recalculate more than we need to.

---

*[prototype2/frontend/doc/schema.md, line 66 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGZSrpypAEiSHAdKF:-KcU8P4EkzLnD3pcmC_5:b-8sd16u) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L66)):*
> We'd need some sort of reverse geo-search though. Firebase doesn't give one to us for free so we'd need to come up with a new schema that can be searched efficiently for this.

Can we associate/aggregate/store that information within Google Maps?  https://developers.google.com/places/.  Beyond storing the geolcations, I'm liking the idea of associating places into Google Maps as well (I spend more time than I'd like to import good places from Swarm into Google Maps).  __FEATURE CREEP__

> Can I add a TODO here as a placeholder?

Yeah, that's cool.  Are we at at point where we can place TODOs as issues in GitHub?

---

*[prototype2/frontend/doc/schema.md, line 90 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRXBTe2Wdc-Csu9YBz:-KcU9hScuciD7ahi2iDD:b1jzbl2) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L90)):*
<details><summary><i>Previously, jasonpetsod (Jason Petsod) wrote…</i></summary><blockquote>

Er, I guess what I said doesn't make sense. We'd set up listeners on `.../budgets/$budgetId/{accounts,categories,payees,transactions}/` and merge all the changes with `this.setState()`. No need to set a listener so deep into the tree.

No strong preference here then.
</blockquote></details>

I'll have to go read the docs again to see how clean fetches/orders/filters will be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by jasonpetsod** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[prototype2/frontend/doc/schema.md, line 10 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcR8mOFFZOimMqgoGJW:-KcWAt8peDbovsUOHQrd:byusytn) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L10)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

Yeah, why not.  I can't think of a better way to do it right now.  It feels like we're hitting too many levels of nesting, though.
</blockquote></details>

Done. But yeah, I agree. We'll probably need to denormalize this a little bit so that when we iterate through budgets (e.g. initial UI page) we don't need to fetch all of the children for each budget.

---

*[prototype2/frontend/doc/schema.md, line 33 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRE_9ViX3zM8lEPalN:-KcWEDm8bxzvT6vAg1kH:b-4gjfxg) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L33)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

> Which total specifically?

As in budget and non-budget accounts.  Once it's hidden, that account no longer considered to be part of that budget.

Separately from that, I think this falls under separation of concerns.  Whether items should get hidden in the UI or not should be saved at the client (cookie/local data/whatever), not within the DB.
</blockquote></details>

As discussed over IM, this is basically only a UI setting and is here so that it's synchronized between the user's clients.

---

*[prototype2/frontend/doc/schema.md, line 55 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGRJQKNI7yyddbCXY:-KcWFrE2YaO9lIXTxkWa:bvmiu7y) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L55)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

The worry is that a transaction may not be cleared until X months later.  In which case, it's likely that we'll need to recalculate more than we need to.
</blockquote></details>

Removed the entire `accountBalances/` tree as discussed. We'll need to gain some mileage with this current schema first to figure out how to add the right optimizations.

---

*[prototype2/frontend/doc/schema.md, line 66 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRGZSrpypAEiSHAdKF:-KcWBXItsMegftZfRJR6:bqasofb) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L66)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

> We'd need some sort of reverse geo-search though. Firebase doesn't give one to us for free so we'd need to come up with a new schema that can be searched efficiently for this.

Can we associate/aggregate/store that information within Google Maps?  https://developers.google.com/places/.  Beyond storing the geolcations, I'm liking the idea of associating places into Google Maps as well (I spend more time than I'd like to import good places from Swarm into Google Maps).  __FEATURE CREEP__

> Can I add a TODO here as a placeholder?

Yeah, that's cool.  Are we at at point where we can place TODOs as issues in GitHub?
</blockquote></details>

Done: added a TODO.

Sure, feel free to add new issues to Github.

---

*[prototype2/frontend/doc/schema.md, line 90 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcRXBTe2Wdc-Csu9YBz:-KcWF7UZW2vY9MiPoqoL:b-4xe0e9) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L90)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

I'll have to go read the docs again to see how clean fetches/orders/filters will be.
</blockquote></details>

Changed to be generated by `Reference.push()` for symmetry as discussed.

---

*[prototype2/frontend/doc/schema.md, line 192 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcROlUopgaQ7BGQfgaH:-KcWI0Anf31-Wu5gTZAP:bwwans3) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L192)):*
<details><summary><i>Previously, jasonpetsod (Jason Petsod) wrote…</i></summary><blockquote>

> Maybe force them to read this field every, say, hour? When we want to kill off old clients, we increment this field, wait a little more than an hour, and then perform the final backfill.

Well, Firebase is _REALTIME_ so we'd set up a listener on `/schemaVersions/` and clients should pick it up "quickly". Probably worth waiting a few minutes for everyone to synchronize nonetheless.

We'll want to set deadlines on transactions though.

Maybe the database isn't the right place for this data. We want this to be ~synchronous but also not require database transactions against `/` to read `minAllowedVersion` _and_ set something deep within e.g. `/users/$userId/budgets/$budgetId/transactions/$txId/`.
</blockquote></details>

All of this replaced with a TODO for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by witriew** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[prototype2/frontend/doc/schema.md, line 1 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcSeMCppzacOwT972zW:-KcWIysiyKC3WTBP6E-y:bw0fvu) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L1)):*
<details><summary><i>Previously, jasonpetsod (Jason Petsod) wrote…</i></summary><blockquote>

Need to move this file to /doc/schema.md once all comments are addressed.
</blockquote></details>

Well?  Where is this!?!?!  BLOCKING ISSUE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by witriew** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-:-KcWJCX4vlRxYCnA5j7b:bnfp4nl)*

**Comment by witriew** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[prototype2/frontend/doc/schema.md, line 1 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcSeMCppzacOwT972zW:-KcWJalTWQQ9N9oPaEhz:bb6o92h) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L1)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

Well?  Where is this!?!?!  BLOCKING ISSUE.
</blockquote></details>

:ok:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by jasonpetsod** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[prototype2/frontend/doc/schema.md, line 1 at r1](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcSeMCppzacOwT972zW:-KcWLModstbtkpoPSKfy:b-896fix) ([raw file](https://github.com/jasonpetsod/loony/blob/5559fd65c61ad46339a19fe20566495172410771/prototype2/frontend/doc/schema.md#L1)):*
<details><summary><i>Previously, witriew (Wit Riewrangboonya) wrote…</i></summary><blockquote>

:ok:
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by jasonpetsod** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by witriew** [comment]
Reviewed 1 of 2 files at r3.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by witriew** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-:-KcWLypIFtG9Jt748O31:bnfp4nl)*

**Comment by jasonpetsod** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Comment by witriew** [comment]
:lgtm: :ok: :ok_hand: :lgtm_strong: :lgtm_cancel: :feelsgood: :denmark: :water_buffalo: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-:-KcWM-qJ7OMGDtSFA1_2:bpp0iwr)*

**Comment by witriew** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[doc/schema.md, line 82 at r3](https://reviewable.io:443/reviews/jasonpetsod/loony/1#-KcWMGwkOdDs-q2g-_jL:-KcWMGwkOdDs-q2g-_jM:bwctgab) ([raw file](https://github.com/jasonpetsod/loony/blob/ccc4319f19c9a7adde7a63b94f2a6cd4df94f60d/doc/schema.md#L82)):*
> ```Markdown
>                 // "YYYY-MM"
>                 month str
>               
> ```

nit: bleeding whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jasonpetsod/loony/1)*

**Pull request merged**
